# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ascp_integration.adapters.proto import ascp_pb2 as ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ascp_integration/adapters/proto/ascp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorServiceStub(object):
    """The ASCP Orchestrator Service allows any agent framework to validate their interactions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginInvocation = channel.unary_unary(
                '/ascp.OrchestratorService/BeginInvocation',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.BeginInvocationRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.BeginInvocationResponse.FromString,
                _registered_method=True)
        self.EndInvocation = channel.unary_unary(
                '/ascp.OrchestratorService/EndInvocation',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.EndInvocationRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.EndInvocationResponse.FromString,
                _registered_method=True)
        self.HookSystemPrompt = channel.unary_unary(
                '/ascp.OrchestratorService/HookSystemPrompt',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.SystemPromptRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.SystemPromptResponse.FromString,
                _registered_method=True)
        self.HookUserInput = channel.unary_unary(
                '/ascp.OrchestratorService/HookUserInput',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.UserInputRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.UserInputResponse.FromString,
                _registered_method=True)
        self.HookPromptGet = channel.unary_unary(
                '/ascp.OrchestratorService/HookPromptGet',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.PromptGetRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.PromptGetResponse.FromString,
                _registered_method=True)
        self.HookRagRetrieval = channel.unary_unary(
                '/ascp.OrchestratorService/HookRagRetrieval',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.RagRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.RagResponse.FromString,
                _registered_method=True)
        self.HookResourceRead = channel.unary_unary(
                '/ascp.OrchestratorService/HookResourceRead',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ResourceReadRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ResourceReadResponse.FromString,
                _registered_method=True)
        self.HookToolCall = channel.unary_unary(
                '/ascp.OrchestratorService/HookToolCall',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolCallResponse.FromString,
                _registered_method=True)
        self.HookToolResult = channel.unary_unary(
                '/ascp.OrchestratorService/HookToolResult',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolResultRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolResultResponse.FromString,
                _registered_method=True)
        self.HookAgentOutput = channel.unary_unary(
                '/ascp.OrchestratorService/HookAgentOutput',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputResponse.FromString,
                _registered_method=True)
        self.HookStreamingAgentOutput = channel.stream_stream(
                '/ascp.OrchestratorService/HookStreamingAgentOutput',
                request_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputRequest.SerializeToString,
                response_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """The ASCP Orchestrator Service allows any agent framework to validate their interactions.
    """

    def BeginInvocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndInvocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookUserInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookPromptGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookRagRetrieval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookResourceRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookToolCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookToolResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookAgentOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HookStreamingAgentOutput(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginInvocation': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginInvocation,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.BeginInvocationRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.BeginInvocationResponse.SerializeToString,
            ),
            'EndInvocation': grpc.unary_unary_rpc_method_handler(
                    servicer.EndInvocation,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.EndInvocationRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.EndInvocationResponse.SerializeToString,
            ),
            'HookSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.HookSystemPrompt,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.SystemPromptRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.SystemPromptResponse.SerializeToString,
            ),
            'HookUserInput': grpc.unary_unary_rpc_method_handler(
                    servicer.HookUserInput,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.UserInputRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.UserInputResponse.SerializeToString,
            ),
            'HookPromptGet': grpc.unary_unary_rpc_method_handler(
                    servicer.HookPromptGet,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.PromptGetRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.PromptGetResponse.SerializeToString,
            ),
            'HookRagRetrieval': grpc.unary_unary_rpc_method_handler(
                    servicer.HookRagRetrieval,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.RagRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.RagResponse.SerializeToString,
            ),
            'HookResourceRead': grpc.unary_unary_rpc_method_handler(
                    servicer.HookResourceRead,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ResourceReadRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ResourceReadResponse.SerializeToString,
            ),
            'HookToolCall': grpc.unary_unary_rpc_method_handler(
                    servicer.HookToolCall,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolCallRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolCallResponse.SerializeToString,
            ),
            'HookToolResult': grpc.unary_unary_rpc_method_handler(
                    servicer.HookToolResult,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolResultRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolResultResponse.SerializeToString,
            ),
            'HookAgentOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.HookAgentOutput,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputResponse.SerializeToString,
            ),
            'HookStreamingAgentOutput': grpc.stream_stream_rpc_method_handler(
                    servicer.HookStreamingAgentOutput,
                    request_deserializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputRequest.FromString,
                    response_serializer=ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascp.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascp.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """The ASCP Orchestrator Service allows any agent framework to validate their interactions.
    """

    @staticmethod
    def BeginInvocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/BeginInvocation',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.BeginInvocationRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.BeginInvocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndInvocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/EndInvocation',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.EndInvocationRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.EndInvocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookSystemPrompt',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.SystemPromptRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.SystemPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookUserInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookUserInput',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.UserInputRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.UserInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookPromptGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookPromptGet',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.PromptGetRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.PromptGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookRagRetrieval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookRagRetrieval',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.RagRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.RagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookResourceRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookResourceRead',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ResourceReadRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ResourceReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookToolCall',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolCallRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookToolResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookToolResult',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolResultRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.ToolResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookAgentOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascp.OrchestratorService/HookAgentOutput',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HookStreamingAgentOutput(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ascp.OrchestratorService/HookStreamingAgentOutput',
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputRequest.SerializeToString,
            ascp__integration_dot_adapters_dot_proto_dot_ascp__pb2.AgentOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
